name: 📖 Publish Docs

on:
  push:
    paths:
      - docs/**
      - osm_merge/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@1.2.4
